if [ -f ~/.bashrc ]; then
source ~/.bashrc
fi

echo 'hi'

test -r /sw/bin/init.sh && . /sw/bin/init.sh

if [ -e /Users/chrisbeard/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/chrisbeard/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

