echo "bashrc"
# Define how Bash prompt looks like:
#
# User @ Host – working dir

set completion-ignore-case on

# http://stackoverflow.com/questions/394230/detect-the-os-from-a-bash-script
platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Darwin' ]]; then
   platform='mac'
elif [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
fi

if [[ $IN_NIX_SHELL != 1 ]]; then
  export PATH=/usr/local/bin:/usr/local/sbin:$PATH
  # https://github.com/mxcl/homebrew/wiki/Homebrew-and-Python
  export PATH=/usr/local/share/python:$PATH
fi

if [[ $platform == 'mac' && ! $IN_NIX_SHELL ]]; then
  export VIRTUALENVWRAPPER_PYTHON=`which python`
  source `which virtualenvwrapper.sh`
elif [[ $platform == 'linux' ]]; then
  alias cd='pushd'
  alias pd='popd'
fi

alias ls='ls $LS_OPTIONS -hF' #human readable, append character indicator
alias ll='ls $LS_OPTIONS -lhF' 	# long listing format
alias l='ls $LS_OPTIONS -lAhF'	# like -a (all) but not the implied . and ..
alias la='ls -a'

# history handling
# Erase duplicates
export HISTCONTROL=erasedups
# resize history size
export HISTSIZE=5000
# append to bash_history if Terminal.app quits
shopt -s histappend

# Nix
# if [ -e ~/.nix-profile/etc/profile.d/nix.sh ]; then
#   . ~/.nix-profile/etc/profile.d/nix.sh;
# fi
export PATH
