alias gi="vim .gitignore"

# Example aliases
alias zshconfig="subl ~/.zshrc"
alias slog="cd /Applications/Slogger && ./slogger"
alias ohmyzsh="subl ~/.oh-my-zsh"
alias bashconfig="subl ~/.bashrc"
alias alsconfig="subl ~/.bash_aliases"
alias vimconfig="subl ~/vimrc.vim"

alias la="ls -a"
alias ll="ls -l"

# $ a.txt # will open the file in subl
alias -s txt=subl

alias octave='octave -q'
alias ipythonq='ipython qtconsole --colors=linux --pylab=inline --InteractiveShellApp.pylab_import_all=False'
alias ins='ipython notebook --script'
alias ins3='ipython3 notebook --pylab=inline --script --InteractiveShellApp.pylab_import_all=False'
# alias ls='ls $LS_OPTIONS -hF' #human readable, append character indicator
# alias ll='ls $LS_OPTIONS -lhF' 	# long listing format
# alias l='ls $LS_OPTIONS -lAhF'	# like -a (all) but not the implied . and ..
# alias la='ls -a'
alias ssh="ssh -X"
alias untar="tar -zxvf"
alias ej="hdiutil eject" # for ejecting
alias dr="cd ~/Dropbox" # dropbox directory
alias dt="cd ~/Desktop" #desktop
alias ~="cd ~/"
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias duh='du -h'
# alias go="gcc -o" #compile with output
# alias ls="ls -G -F -C" # G: colored; F: slash after Directory C: multi column
alias vlc='/Applications/VLC.app/Contents/MacOS/VLC'
alias dat="cd ~/Dropbox/Engineering/data/"
alias sp="cd /usr/local/lib/python2.7/site-packages/"
alias pc="pwd | pbcopy"
alias pd='popd'
unalias gc >/dev/null 2>/dev/null
alias gc="git clone"
alias gpl="git pull"
alias pi="pip install"
alias pf="pip freeze"
alias hist="tac ~/.zsh_history | sed -E 's/\: [0-9]+\:0;(.+)/\\1/' | less"
alias gig="vim `git config --global core.excludesfile`"
alias wo="workon"

alias ca="source activate"
alias sd="source deactivate"
alias mkc="conda create --name"
alias cl="conda list"
alias ce="conda env"
alias ceu="conda env update"
alias cec="conda env create"

# Git
# alias summ="git log --all --graph --pretty=format:'%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
alias summ="git log --pretty=format:'%C(yellow)%h%Cred%d %Creset%s' --decorate --numstat"

# Cabal
alias ghc-sandbox="ghc -no-user-package-db -package-db .cabal-sandbox/*-packages.conf.d"
alias ghci-sandbox="ghci -no-user-package-db -package-db .cabal-sandbox/*-packages.conf.d"
alias runhaskell-sandbox="runhaskell -no-user-package-db -package-db .cabal-sandbox/*-packages.conf.d"
alias nix-search="nix-env -qaP --description '*' | grep"
alias nixs="nix-env -q --installed"
alias cabalz="cabal exec zsh"
alias cz="cabal exec zsh"
# alias cl="cabal list --installed"
alias gsh="nix-shell -p 'ghc.ghc782'"

alias busy="cat /dev/urandom | hexdump -C | grep 'ca fe'"
alias clean="iconv -c -f ISO-8859-1 -t ASCII"
alias dw="/Volumes/C/Users/beardc01/Desktop/"
pb="/Volumes/C/Users/beardc01/Desktop/pasteboard.txt"
alias ipj="ipython notebook --profile julia"

alias julia="/Applications/Julia-0.4*/Contents/Resources/julia/bin/julia"
# alias julia="/Applications/Julia-0.3.1.app/Contents/Resources/julia/bin/julia"
# ln -s /Applications/Julia-0.3.1.app/Contents/Resources/julia/bin/julia /usr/local/bin/julia
# alias julia="exec '/Applications/Julia-0.3.1.app/Contents/Resources/julia/bin/julia'"
# alias psc-make=~/repos/scatter/.cabal-sandbox/bin/psc-make
