alias gi="vim .gitignore"

# Example aliases
alias zshconfig="subl ~/.zshrc"
alias slog="cd /Applications/Slogger && ./slogger"
alias ohmyzsh="subl ~/.oh-my-zsh"
alias bashconfig="subl ~/.bashrc"
alias alsconfig="subl ~/.bash_aliases"
alias vimconfig="subl ~/vimrc.vim"

alias la="ls -a"
alias ll="ls -l"

# $ a.txt # will open the file in subl
alias -s txt=subl

alias octave='octave -q'
alias ipythonq='ipython qtconsole --colors=linux --pylab=inline --InteractiveShellApp.pylab_import_all=False'
alias ins='ipython notebook --script'
alias ins3='ipython3 notebook --pylab=inline --script --InteractiveShellApp.pylab_import_all=False'
# alias ls='ls $LS_OPTIONS -hF' #human readable, append character indicator
# alias ll='ls $LS_OPTIONS -lhF' 	# long listing format
# alias l='ls $LS_OPTIONS -lAhF'	# like -a (all) but not the implied . and ..
# alias la='ls -a'
alias ssh="ssh -X"
alias untar="tar -zxvf"
alias ej="hdiutil eject" # for ejecting
alias dr="cd ~/Dropbox" # dropbox directory
alias dt="cd ~/Desktop" #desktop
alias ~="cd ~/"
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias duh='du -h'
# alias go="gcc -o" #compile with output
# alias ls="ls -G -F -C" # G: colored; F: slash after Directory C: multi column
alias vlc='/Applications/VLC.app/Contents/MacOS/VLC'
alias dat="cd ~/Dropbox/Engineering/data/"
alias sp="cd /usr/local/lib/python2.7/site-packages/"
alias pc="pwd | pbcopy"
alias pd='popd'
unalias gc >/dev/null 2>/dev/null
alias gc="git clone"
alias gpl="git pull"
alias pi="pip install"
alias pf="pip freeze"
alias hist="tac ~/.zsh_history | sed -E 's/\: [0-9]+\:0;(.+)/\\1/' | less"
alias gig="vim `git config --global core.excludesfile`"
alias wo="workon"

# Cabal
alias ghc-sandbox="ghc -no-user-package-db -package-db .cabal-sandbox/*-packages.conf.d"
alias ghci-sandbox="ghci -no-user-package-db -package-db .cabal-sandbox/*-packages.conf.d"
alias runhaskell-sandbox="runhaskell -no-user-package-db -package-db .cabal-sandbox/*-packages.conf.d"
alias nix-search="nix-env -qaP --description '*' | grep"
alias nixs="nix-env -q --installed"
alias cabalz="cabal exec zsh"
alias cz="cabal exec zsh"
alias cl="cabal list --installed"
alias gsh="nix-shell -p 'ghc.ghc783'"
alias nemacs="nix-shell -p 'ghc.ghc783'; /Applications/Emacs.app/Contents/MacOS/Emacs '$@'"

alias clean="iconv -c -f ISO-8859-1 -t ASCII"
alias dw="/Volumes/C/Users/beardc01/Desktop/"
pb="/Volumes/C/Users/beardc01/Desktop/pasteboard.txt"
alias ipj="ipython notebook --profile julia"
