# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"
setopt extendedglob
set completion-ignore-case on
export HISTCONTROL=erasedups
export HISTSIZE=5000
# shopt -s histappend  # append to bash_history if Terminal.app quits
export USE_LIBPCRE=yes

export LESSOPEN="| src-hilite-lesspipe.sh %s"
export LESS=" -R "

plugins=(git brew pip python sublime vagrant neo4j mysql.server postgres
 gem npm bower tmux screen vundle cabal docker cp autopep8)

# http://stackoverflow.com/a/394235/386279
case $OSTYPE in
  darwin*) platform=mac ;;
  linux*) platform=linux;;
  *) platform=other;;
esac

if [[ $platform == 'mac' && -f ~/.mac_zsh ]]; then
  . ~/.mac_zsh
elif [[ $platform == 'linux' ]]; then
  . ~/.linux_zsh
fi


# Nix
if [[ $IN_NIX_SHELL != 1 ]]; then
  # No Nix
  export PATH=/usr/local/bin:/usr/local/sbin:$PATH
  export PATH=/usr/local/Cellar/ruby/1.9.3-p194/bin:$PATH
  export PATH=/usr/local/share/npm/bin:$PATH
  else
    # export PATH=/usr/bin:/bin:/usr/sbin:/sbin
    source /Users/chrisbeard/dotfiles/files/dots/.nix_zshrc
    # return
fi

if [[ (-e ~/.nix-profile/etc/profile.d/nix.sh) ]]; then
  . ~/.nix-profile/etc/profile.d/nix.sh;
fi


# LOCAL PYTHON PATH
# export PYTHONPATH="/usr/local/lib/python2.7/site-packages:$PYTHONPATH"
export PYTHONPATH=~/src:$PYTHONPATH
export PYTHONPATH=~/src/myutils/:$PYTHONPATH
export PYTHONPATH=~/repos/ora_utils:$PYTHONPATH
export PYTHONPATH=~/repos:$PYTHONPATH
export PATH=~/src:$PATH
export PATH=~/repos/ora_utils:$PATH

export PYTHONDONTWRITEBYTECODE=True
export PATH=/usr/local/opt/ruby/bin:$PATH
# APPDATA=$HOME/.runsnake

# PACKAGE CONFIGURATION PATH
# from http://www.linuxquestions.org/questions/linux-software-2/how-do-i-add-to-the-pkg_config_path-environment-variable-619202/
export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig

# Pycuda
export CUDA_ROOT=/usr/local/cuda/bin
export PATH=/usr/local/cuda/bin:$PATH

# tips
# textutil -convert doc /path/to/my/file.docx #to convert text documents
# if completion gets buggered, run `rm -f ~.zcompdump-chrisbeard*`

echo $VIRTUALENVWRAPPER_PYTHON
source $ZSH/oh-my-zsh.sh

# Load after plugins (gc alias conflict)
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

agpy () {
  ag "$@" **/*.py
}

# Add GHC 7.8.3 to the PATH, via http://ghcformacosx.github.io/
export GHC_DOT_APP="/Applications/ghc-7.8.4.app"
if [ -d "$GHC_DOT_APP" ]; then
    export PATH="${HOME}/.cabal/bin:${GHC_DOT_APP}/Contents/bin:${PATH}"
fi
export PATH="${HOME}/repos/scatter/.cabal-sandbox/bin:${PATH}"
# Cabal sandbox
function cabal_sandbox_info() {
    cabal_files=(*.cabal(N))
    if [ $#cabal_files -gt 0 ]; then
        if [ -f cabal.sandbox.config ]; then
            echo "%{$fg[green]%}sandboxed%{$reset_color%}"
        else
            echo "%{$fg[red]%}not sandboxed%{$reset_color%}"
        fi
    fi
}
RPROMPT="\$(cabal_sandbox_info) $RPROMPT"
export PATH=~/.cabal/bin:$PATH

# system
umask 0002 # group write permission

# added by Miniconda3 3.19.0 installer
export PATH="/Users/williambeard/miniconda3/bin:$PATH"

# Rust
# export DYLD_LIBRARY_PATH='/usr/local/lib'
export RUST_SRC_PATH=~/src/rust/src

# Setting PATH for Python 3.1
# The orginal version is saved in .bash_profile.pysave
# PATH="${PATH}:/Library/Frameworks/Python.framework/Versions/3.1/bin"
export TERM=xterm-256color
export PATH
